# For more information: https://laravel.com/docs/sail
services:
    athena:
        container_name: athena
        build:
            context: ./docker/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '/opt/docker/data/athena:/var/www/html'
        networks:
            - sail
            - traefik
        depends_on:
            - redis
            - mongodb
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.athena.rule=Host(`athena.wynntils.com`)"

    redis:
        image: 'redis:alpine'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

    mongodb:
        image: mongo:latest
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - 'mongodb-data:/data/db'
        networks:
            - sail
networks:
    sail:
    traefik:
        external: true

volumes:
    sail-redis:
    mongodb-data:
